name: test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements.dev.txt'
    - name: lint
      run: |
        pip install -r requirements.dev.txt
        make lint
        make typecheck
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    - name: test
      run: |
        pip install -r requirements.txt
        make test
